Repository Check-Data-Out/velog-dashboard-v2-back-office, pull requests merged in 2025-03, with the labels that each got.

#19 [25.03.02 / TASK-129] Feature - user admin action
  .coveragerc
  .github/workflows/run-daily-target-aggre.yaml
  README.md
  backoffice/settings/base.py
  backoffice/settings/prod.py
  posts/admin.py
  scraping/aggregate_batch.py
  scraping/main.py
  users/admin.py
  users/tests.py
  users/tests/__init__.py
  users/tests/conftest.py
  users/tests/test_user_admin.py
Labels: documentation, enhancement

#20 [25.03.07 / TASK-84] Test - Scraper 테스트 코드 구현
  .github/workflows/test-ci.yaml
  scraping/main.py
  scraping/tests/test_main.py
  scraping/tests/test_sample.py
Labels: documentation, enhancement

#22 [25.03.15 / TASK-143] Delete: 이벤트 추적 관련 모든 파일 삭제
  backoffice/settings/base.py
  tracking/__init__.py
  tracking/admin.py
  tracking/apps.py
  tracking/migrations/0001_initial.py
  tracking/migrations/0002_alter_usereventtracking_options.py
  tracking/migrations/0003_userstaytime.py
  tracking/migrations/0004_remove_userstaytime_created_at.py
  tracking/migrations/0005_usereventtracking_request_header_and_more.py
  tracking/migrations/__init__.py
  tracking/models.py
  tracking/tests/__init__.py
  tracking/tests/test_staytime_model_spec.py
  tracking/tests/test_tracking_model_spec.py
Labels: bug, documentation, enhancement

#23 [25.03.25 / TASK-152] Hotfix: QRLoginToken 조회 시 N+1 문제 해결
  users/admin.py
  users/tests/test_qrcode_admin.py
  users/tests/test_user_admin.py
Labels: bug

#24 [25.03.15 / TASK-138] Feature: sentry 추가
  .env.sample
  backoffice/settings/base.py
  backoffice/urls.py
  poetry.lock
  pyproject.toml
  requirements.txt
  scraping/main.py
Labels: enhancement

#25 [25.03.29 / TASK-150] Feature - batch post upsert
  .env.sample
  .github/workflows/test-ci.yaml
  .pre-commit-config.yaml
  README.md
  backoffice/settings/base.py
  backoffice/settings/test.py
  mypy.ini
  pyproject.toml
  scraping/main.py
  scraping/tests/test_main.py
  users/models.py
Labels: bug, documentation
